package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
)

// TypeDefinition 型定義の情報
type TypeDefinition struct {
	Name        string
	Description string
	Fields      []FieldDefinition
}

// FieldDefinition フィールド定義の情報
type FieldDefinition struct {
	Name        string
	Type        string
	Description string
	Required    bool
}

// 抽出する型のリスト（必要に応じて追加）
var typesToExtract = []string{
	"User",
	"Repository",
	"RepositoryOwner",
	"Language",
	"Commit",
	"CommitHistory",
	"PageInfo",
	"ContributionsCollection",
	"CommitContributionsByRepository",
	"RepositoryConnection",
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "Usage: %s <schema.docs.graphql> [output-dir]\n", os.Args[0])
		os.Exit(1)
	}

	schemaPath := os.Args[1]
	outputDir := "internal/graphql/generated"
	if len(os.Args) > 2 {
		outputDir = os.Args[2]
	}

	fmt.Printf("📖 スキーマファイルを読み込み中: %s\n", schemaPath)
	types, err := parseSchema(schemaPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "エラー: スキーマの解析に失敗しました: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✅ %d個の型定義を抽出しました\n", len(types))

	// 出力ディレクトリを作成
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "エラー: 出力ディレクトリの作成に失敗しました: %v\n", err)
		os.Exit(1)
	}

	// 型定義を生成
	outputPath := filepath.Join(outputDir, "types.go")
	fmt.Printf("📝 型定義を生成中: %s\n", outputPath)
	if err := generateTypes(outputPath, types); err != nil {
		fmt.Fprintf(os.Stderr, "エラー: 型定義の生成に失敗しました: %v\n", err)
		os.Exit(1)
	}

	// クエリ構造体を生成
	queryPath := filepath.Join(outputDir, "queries.go")
	fmt.Printf("📝 クエリ構造体を生成中: %s\n", queryPath)
	if err := generateQueries(queryPath); err != nil {
		fmt.Fprintf(os.Stderr, "エラー: クエリ構造体の生成に失敗しました: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("✅ コード生成が完了しました！")
}

// parseSchema GraphQLスキーマファイルを解析して型定義を抽出
func parseSchema(path string) (map[string]TypeDefinition, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("ファイルを開けませんでした: %w", err)
	}
	defer file.Close()

	types := make(map[string]TypeDefinition)
	scanner := bufio.NewScanner(file)

	var currentType *TypeDefinition
	var inTypeDefinition bool

	typePattern := regexp.MustCompile(`^type\s+(\w+)\s*(implements\s+[\w\s&]+)?\s*\{`)
	fieldPattern := regexp.MustCompile(`^\s+(\w+)\s*:\s*([!\w\[\]\(\),&\s]+)`)

	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)

		// 型定義の開始を検出
		if matches := typePattern.FindStringSubmatch(line); matches != nil {
			typeName := matches[1]
			if contains(typesToExtract, typeName) {
				currentType = &TypeDefinition{
					Name:   typeName,
					Fields: []FieldDefinition{},
				}
				types[typeName] = *currentType
				inTypeDefinition = true
				continue
			}
		}

		// 型定義の中にあるフィールドを抽出
		if inTypeDefinition && currentType != nil {
			if trimmed == "}" || trimmed == "}" {
				inTypeDefinition = false
				currentType = nil
				continue
			}

			if matches := fieldPattern.FindStringSubmatch(line); matches != nil {
				fieldName := matches[1]
				fieldType := strings.TrimSpace(matches[2])
				required := strings.HasSuffix(fieldType, "!")

				field := FieldDefinition{
					Name:     fieldName,
					Type:     fieldType,
					Required: required,
				}
				// currentTypeを更新する必要があるため、mapから取得して更新
				if t, ok := types[currentType.Name]; ok {
					t.Fields = append(t.Fields, field)
					types[currentType.Name] = t
				}
			}
		}
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("スキャンエラー: %w", err)
	}

	return types, nil
}

// contains スライスに要素が含まれているかチェック
func contains(slice []string, item string) bool {
	for _, s := range slice {
		if s == item {
			return true
		}
	}
	return false
}

// generateTypes 型定義のGoコードを生成
func generateTypes(outputPath string, types map[string]TypeDefinition) error {
	tmpl := `// Code generated by tools/generate-github-types/main.go. DO NOT EDIT.

package generated

import (
	"time"
)

{{range .Types}}
// {{.Name}} {{.Description}}
type {{.Name}} struct {
{{range .Fields}}
	{{.Name | title}} {{.Type | goType}} ` + "`" + `graphql:"{{.Name}}"` + "`" + `{{end}}
}
{{end}}
`

	funcMap := template.FuncMap{
		"title": strings.Title,
		"goType": func(gqlType string) string {
			return convertGraphQLTypeToGo(gqlType)
		},
	}

	t := template.Must(template.New("types").Funcs(funcMap).Parse(tmpl))

	data := struct {
		Types []TypeDefinition
	}{
		Types: extractTypesInOrder(types),
	}

	file, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("ファイルを作成できませんでした: %w", err)
	}
	defer file.Close()

	return t.Execute(file, data)
}

// generateQueries クエリ構造体のGoコードを生成
func generateQueries(outputPath string) error {
	tmpl := `// Code generated by tools/generate-github-types/main.go. DO NOT EDIT.

package generated

// ViewerQuery 認証ユーザー情報を取得するクエリ
type ViewerQuery struct {
	Viewer User ` + "`" + `graphql:"viewer"` + "`" + `
}

// ReposQueryVariables リポジトリクエリの変数
type ReposQueryVariables struct {
	Login  string  ` + "`" + `json:"login"` + "`" + `
	IsFork *bool   ` + "`" + `json:"isFork,omitempty"` + "`" + `
	First  *int    ` + "`" + `json:"first,omitempty"` + "`" + `
	After  *string ` + "`" + `json:"after,omitempty"` + "`" + `
}

// ReposQuery リポジトリ情報を取得するクエリ
type ReposQuery struct {
	User struct {
		Repositories struct {
			Nodes    []Repository ` + "`" + `graphql:"nodes"` + "`" + `
			PageInfo PageInfo     ` + "`" + `graphql:"pageInfo"` + "`" + `
		} ` + "`" + `graphql:"repositories(isFork: $isFork, first: $first, after: $after, ownerAffiliations: OWNER)"` + "`" + `
	} ` + "`" + `graphql:"user(login: $login)"` + "`" + `
}
`

	file, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("ファイルを作成できませんでした: %w", err)
	}
	defer file.Close()

	_, err = file.WriteString(tmpl)
	return err
}

// convertGraphQLTypeToGo GraphQL型をGo型に変換
func convertGraphQLTypeToGo(gqlType string) string {
	gqlType = strings.TrimSpace(gqlType)
	required := strings.HasSuffix(gqlType, "!")
	if required {
		gqlType = strings.TrimSuffix(gqlType, "!")
	}

	// 配列型の処理
	if strings.HasPrefix(gqlType, "[") && strings.HasSuffix(gqlType, "]") {
		inner := strings.TrimPrefix(strings.TrimSuffix(gqlType, "]"), "[")
		goType := convertGraphQLTypeToGo(inner)
		result := "[]" + goType
		if !required {
			result = "*" + result
		}
		return result
	}

	// 基本的な型のマッピング
	switch gqlType {
	case "String":
		if required {
			return "string"
		}
		return "*string"
	case "Int":
		if required {
			return "int"
		}
		return "*int"
	case "Float":
		if required {
			return "float64"
		}
		return "*float64"
	case "Boolean":
		if required {
			return "bool"
		}
		return "*bool"
	case "ID":
		if required {
			return "string"
		}
		return "*string"
	case "DateTime", "GitTimestamp":
		if required {
			return "time.Time"
		}
		return "*time.Time"
	case "URI":
		if required {
			return "string"
		}
		return "*string"
	default:
		// カスタム型（User, Repositoryなど）
		if required {
			return gqlType
		}
		return "*" + gqlType
	}
}

// extractTypesInOrder 型を順序よく抽出
func extractTypesInOrder(types map[string]TypeDefinition) []TypeDefinition {
	var result []TypeDefinition
	for _, typeName := range typesToExtract {
		if t, ok := types[typeName]; ok {
			result = append(result, t)
		}
	}
	return result
}
