name: 'Update GitHub Profile'
description: '認証ユーザー自身の GitHub リポジトリメトリクスを取得して、README.md を更新する'
inputs:
  github_token:
    description: 'GitHub Personal Access Token（リポジトリ情報読み取り用、すべてのリポジトリを読み取る権限が必要）'
    required: false
  exclude_forks:
    description: 'フォークリポジトリを除外するかどうか（true/false）'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ github.action_path }}/go.mod

    - name: Download dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        go mod download

    - name: Fetch user repositories
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        echo "::group::リポジトリ一覧を取得"
        export GITHUB_TOKEN="${{ inputs.github_token }}"

        EXCLUDE_FORKS="${{ inputs.exclude_forks }}"
        if [ -z "$EXCLUDE_FORKS" ]; then
          EXCLUDE_FORKS="true"
        fi

        # リポジトリ一覧を取得（認証ユーザー自身のリポジトリのみ）
        # 認証ユーザーは自動的に取得されます
        go run ./cmd/update-gh-profile/main.go --exclude-forks="$EXCLUDE_FORKS" || exit 1
        echo "::endgroup::"

