name: 'Update GitHub Profile'
description: 'Fetches GitHub repository metrics for the authenticated user and updates README.md'
inputs:
  github_token:
    description: 'GitHub Personal Access Token (for reading repository information, requires permission to read all repositories)'
    required: false
  exclude_forks:
    description: 'Whether to exclude forked repositories (true/false)'
    required: false
    default: 'true'
  exclude_languages:
    description: 'Language names to exclude from ranking (comma-separated, e.g., JSON,Markdown,Text)'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ github.action_path }}/go.mod

    - name: Download dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        go mod download

    - name: Fetch user repositories
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        EXCLUDE_LANGUAGES: ${{ inputs.exclude_languages }}
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        echo "::group::Fetching repository list"
        export GITHUB_TOKEN="${{ inputs.github_token }}"

        EXCLUDE_FORKS="${{ inputs.exclude_forks }}"
        if [ -z "$EXCLUDE_FORKS" ]; then
          EXCLUDE_FORKS="true"
        fi

        # Set excluded languages as environment variable (don't set if empty)
        if [ -n "${{ inputs.exclude_languages }}" ]; then
          export EXCLUDE_LANGUAGES="${{ inputs.exclude_languages }}"
        fi

        # Fetch repository list (only repositories owned by authenticated user)
        # Authenticated user is automatically fetched
        go run ./cmd/update-gh-profile/main.go --exclude-forks="$EXCLUDE_FORKS" || exit 1
        echo "::endgroup::"

