// Code generated by tools/generate-github-types/main.go. DO NOT EDIT.
// To regenerate: go run ../../tools/generate-github-types/main.go ../../schema.docs.graphql .

package graphql

import (
	"time"

	"github.com/hasura/go-graphql-client"
)

// ============================================================================
// 基本型定義
// ============================================================================

// User GitHubユーザー情報
type User struct {
	Login     string `graphql:"login"`
	ID        string `graphql:"id"`
	Name      string `graphql:"name"`
	Email     string `graphql:"email"`
	AvatarURL string `graphql:"avatarUrl"`
	Bio       string `graphql:"bio"`
	Company   string `graphql:"company"`
	CreatedAt string `graphql:"createdAt"`
	UpdatedAt string `graphql:"updatedAt"`
}

// RepositoryOwner リポジトリオーナー
type RepositoryOwner struct {
	Login string `graphql:"login"`
	ID    string `graphql:"id"`
}

// Language プログラミング言語情報
type Language struct {
	Name  string `graphql:"name"`
	Color string `graphql:"color"`
}

// PageInfo ページネーション情報
type PageInfo struct {
	EndCursor       string `graphql:"endCursor"`
	HasNextPage     bool   `graphql:"hasNextPage"`
	StartCursor     string `graphql:"startCursor"`
	HasPreviousPage bool   `graphql:"hasPreviousPage"`
}

// Repository リポジトリ情報
type Repository struct {
	Name             string          `graphql:"name"`
	Owner            RepositoryOwner `graphql:"owner"`
	PrimaryLanguage  *Language       `graphql:"primaryLanguage"`
	StargazerCount   int             `graphql:"stargazerCount"`
	ForkCount        int             `graphql:"forkCount"`
	IsFork           bool            `graphql:"isFork"`
	IsPrivate        bool            `graphql:"isPrivate"`
	CreatedAt        time.Time       `graphql:"createdAt"`
	UpdatedAt        time.Time       `graphql:"updatedAt"`
	DefaultBranchRef *struct {
		Target struct {
			Commit struct {
				History CommitHistory `graphql:"history(first: 100)"`
			} `graphql:"... on Commit"`
		} `graphql:"target"`
	} `graphql:"defaultBranchRef"`
	Languages *LanguageConnection `graphql:"languages(first: 100)"`
}

// LanguageConnection 言語のコネクション
type LanguageConnection struct {
	Nodes []Language `graphql:"nodes"`
	Edges []struct {
		Node Language `graphql:"node"`
		Size int      `graphql:"size"`
	} `graphql:"edges"`
	TotalSize int `graphql:"totalSize"`
}

// LanguageNode 言語ノード（後方互換性のため残すが、実際にはLanguageを使用）
type LanguageNode struct {
	Name string `graphql:"name"`
	Size int    `graphql:"size"`
}

// CommitHistory コミット履歴
type CommitHistory struct {
	TotalCount int       `graphql:"totalCount"`
	Nodes      []*Commit `graphql:"nodes"`
}

// Commit コミット情報
type Commit struct {
	CommittedDate time.Time `graphql:"committedDate"`
	Message       string    `graphql:"message"`
	Author        *struct {
		Name  string    `graphql:"name"`
		Email string    `graphql:"email"`
		Date  time.Time `graphql:"date"`
	} `graphql:"author"`
	Additions int `graphql:"additions"`
	Deletions int `graphql:"deletions"`
}

// ContributionsCollection コントリビューションコレクション
type ContributionsCollection struct {
	CommitContributionsByRepository []CommitContributionsByRepository `graphql:"commitContributionsByRepository(maxRepositories: 100)"`
	ContributionCalendar            *ContributionCalendar             `graphql:"contributionCalendar"`
}

// CommitContributionsByRepository リポジトリごとのコミットコントリビューション
type CommitContributionsByRepository struct {
	Repository    Repository `graphql:"repository"`
	Contributions struct {
		TotalCount int `graphql:"totalCount"`
	} `graphql:"contributions"`
}

// ContributionCalendar コントリビューションカレンダー
type ContributionCalendar struct {
	Weeks []ContributionWeek `graphql:"weeks"`
}

// ContributionWeek コントリビューション週
type ContributionWeek struct {
	ContributionDays []ContributionDay `graphql:"contributionDays"`
}

// ContributionDay コントリビューションデー
type ContributionDay struct {
	ContributionCount int    `graphql:"contributionCount"`
	Date              string `graphql:"date"`
}

// ============================================================================
// クエリ構造体
// ============================================================================

// ViewerQuery 認証ユーザー情報を取得するクエリ
type ViewerQuery struct {
	Viewer User `graphql:"viewer"`
}

// UserDetailsQueryVariables ユーザー詳細クエリの変数
type UserDetailsQueryVariables struct {
	Login string `json:"login"`
}

// UserDetailsQuery ユーザー詳細情報を取得するクエリ
type UserDetailsQuery struct {
	User struct {
		ID                      string                   `graphql:"id"`
		Name                    string                   `graphql:"name"`
		Email                   string                   `graphql:"email"`
		CreatedAt               string                   `graphql:"createdAt"`
		Repositories            *RepositoryConnection    `graphql:"repositories(first: 100, privacy: PUBLIC, isFork: false, ownerAffiliations: OWNER, orderBy: {direction: DESC, field: STARGAZERS})"`
		ContributionsCollection *ContributionsCollection `graphql:"contributionsCollection"`
		PullRequests            *struct {
			TotalCount int `graphql:"totalCount"`
		} `graphql:"pullRequests(first: 1)"`
		Issues *struct {
			TotalCount int `graphql:"totalCount"`
		} `graphql:"issues(first: 1)"`
	} `graphql:"user(login: $login)"`
}

// RepositoryConnection リポジトリコネクション
type RepositoryConnection struct {
	TotalCount int          `graphql:"totalCount"`
	Nodes      []Repository `graphql:"nodes"`
	PageInfo   PageInfo     `graphql:"pageInfo"`
}

// ReposQueryVariables リポジトリクエリの変数
type ReposQueryVariables struct {
	Login  string  `json:"login"`
	IsFork *bool   `json:"isFork,omitempty"`
	First  *int    `json:"first,omitempty"`
	After  *string `json:"after,omitempty"`
}

// ReposQuery リポジトリ情報を取得するクエリ
// 変数は構造体のgraphqlタグに直接埋め込む
type ReposQuery struct {
	User struct {
		Repositories struct {
			Nodes    []Repository `graphql:"nodes"`
			PageInfo PageInfo     `graphql:"pageInfo"`
		} `graphql:"repositories(isFork: $isFork, first: $first, after: $after, ownerAffiliations: OWNER)"`
	} `graphql:"user(login: $login)"`
}

// ReposQueryVars リポジトリクエリの変数定義
// hasura/go-graphql-clientでは、変数はクエリ構造体とは別に定義する必要がある場合がある
// ただし、実際にはmap[string]interface{}で直接渡すため、この構造体は参考用
type ReposQueryVars struct {
	Login  string  `json:"login"`
	IsFork *bool   `json:"isFork,omitempty"`
	First  *int    `json:"first,omitempty"`
	After  *string `json:"after,omitempty"`
}

// CommitLanguagesQueryVariables コミット言語クエリの変数
type CommitLanguagesQueryVariables struct {
	Login string `json:"login"`
}

// CommitLanguagesQuery コミットごとの言語使用状況を取得するクエリ
type CommitLanguagesQuery struct {
	User struct {
		ContributionsCollection *ContributionsCollection `graphql:"contributionsCollection"`
	} `graphql:"user(login: $login)"`
}

// ProductiveTimeQueryVariables コミット時間帯クエリの変数
type ProductiveTimeQueryVariables struct {
	Login  string `json:"login"`
	UserID string `json:"userId"`
	Since  string `json:"since"`
	Until  string `json:"until"`
}

// ProductiveTimeQuery コミット時間帯を取得するクエリ
type ProductiveTimeQuery struct {
	User struct {
		ContributionsCollection *ContributionsCollection `graphql:"contributionsCollection"`
	} `graphql:"user(login: $login)"`
}

// ============================================================================
// ヘルパー関数
// ============================================================================

// NewGraphQLClient GraphQLクライアントを作成
func NewGraphQLClient(endpoint string, token string) *graphql.Client {
	// この関数は実際の実装で置き換えられます
	return graphql.NewClient(endpoint, nil)
}
